/**
 * 浏览器 KeyboardEvent.code → 布局 keyId（KC_*）。
 * 只用物理键位，不读 event.key（避免输入法/键位布局干扰）。
 * KC_FN 与增补区重复 id 不映射。
 */

const CODE_TO_KEY_ID: Readonly<Record<string, string>> = {
  Escape: "KC_ESC",
  F1: "KC_F1",
  F2: "KC_F2",
  F3: "KC_F3",
  F4: "KC_F4",
  F5: "KC_F5",
  F6: "KC_F6",
  F7: "KC_F7",
  F8: "KC_F8",
  F9: "KC_F9",
  F10: "KC_F10",
  F11: "KC_F11",
  F12: "KC_F12",
  PrintScreen: "KC_PSCR",
  ScrollLock: "KC_SLCK",
  Pause: "KC_PAUS",

  Backquote: "KC_GRV",
  Digit1: "KC_1",
  Digit2: "KC_2",
  Digit3: "KC_3",
  Digit4: "KC_4",
  Digit5: "KC_5",
  Digit6: "KC_6",
  Digit7: "KC_7",
  Digit8: "KC_8",
  Digit9: "KC_9",
  Digit0: "KC_0",
  Minus: "KC_MINS",
  Equal: "KC_EQL",
  Backspace: "KC_BSPC",

  Tab: "KC_TAB",
  KeyQ: "KC_Q",
  KeyW: "KC_W",
  KeyE: "KC_E",
  KeyR: "KC_R",
  KeyT: "KC_T",
  KeyY: "KC_Y",
  KeyU: "KC_U",
  KeyI: "KC_I",
  KeyO: "KC_O",
  KeyP: "KC_P",
  BracketLeft: "KC_LBRC",
  BracketRight: "KC_RBRC",
  Backslash: "KC_BSLS",

  CapsLock: "KC_CAPS",
  KeyA: "KC_A",
  KeyS: "KC_S",
  KeyD: "KC_D",
  KeyF: "KC_F",
  KeyG: "KC_G",
  KeyH: "KC_H",
  KeyJ: "KC_J",
  KeyK: "KC_K",
  KeyL: "KC_L",
  Semicolon: "KC_SCLN",
  Quote: "KC_QUOT",
  Enter: "KC_ENT",

  ShiftLeft: "KC_LSFT",
  KeyZ: "KC_Z",
  KeyX: "KC_X",
  KeyC: "KC_C",
  KeyV: "KC_V",
  KeyB: "KC_B",
  KeyN: "KC_N",
  KeyM: "KC_M",
  Comma: "KC_COMM",
  Period: "KC_DOT",
  Slash: "KC_SLSH",
  ShiftRight: "KC_RSFT",

  ControlLeft: "KC_LCTL",
  MetaLeft: "KC_LGUI",
  AltLeft: "KC_LALT",
  Space: "KC_SPC",
  AltRight: "KC_RALT",
  MetaRight: "KC_RGUI",
  ContextMenu: "KC_APP",
  ControlRight: "KC_RCTL",

  Insert: "KC_INS",
  Home: "KC_HOME",
  PageUp: "KC_PGUP",
  Delete: "KC_DEL",
  End: "KC_END",
  PageDown: "KC_PGDN",
  ArrowUp: "KC_UP",
  ArrowDown: "KC_DOWN",
  ArrowLeft: "KC_LEFT",
  ArrowRight: "KC_RGHT",

  NumLock: "KC_NLCK",
  NumpadDivide: "KC_PSLS",
  NumpadMultiply: "KC_PAST",
  NumpadSubtract: "KC_PMNS",
  NumpadAdd: "KC_PPLS",
  NumpadEnter: "KC_PENT",
  Numpad1: "KC_P1",
  Numpad2: "KC_P2",
  Numpad3: "KC_P3",
  Numpad4: "KC_P4",
  Numpad5: "KC_P5",
  Numpad6: "KC_P6",
  Numpad7: "KC_P7",
  Numpad8: "KC_P8",
  Numpad9: "KC_P9",
  Numpad0: "KC_P0",
  NumpadDecimal: "KC_PDOT",

  AudioVolumeMute: "KC_MUTE",
  AudioVolumeDown: "KC_VOLD",
  AudioVolumeUp: "KC_VOLU",
  LaunchApplication2: "KC_CALC",
}

export function codeToKeyId(code: string): string | null {
  return CODE_TO_KEY_ID[code] ?? null
}
